### ISSUE TITLE
IMPROVE THE README PLZ!

### ISSUE THREAD

**Issue by EliasSalom** [pubcore/iso-language-codes#10]
please edit the readme with a better explanation and code example, this will make the package more useful, 
it's really a code package but you need to add more documentation
like if you can add sections like

1. what's include 
2. support `typescript`
3. work with `ECMAScript` **5 and 6** with an example `require` and `import`

with titles and indexes

I can help with this if you want!

**Comment by jacklrs** [comment]
Feel free to create a pull request!

**Comment by EliasSalom** [comment]
I tried to open a `PR` but I can't push the new code, please if you can add me to the `repo` @jacklrs

**Comment by jacklrs** [comment]
I assume the standard way to contribute should work.  Here is what I mean:
https://github.com/firstcontributions/first-contributions
