### ISSUE TITLE
error TS7016: Could not find a declaration file for module 'iso-language-codes'. './node_modules/iso-language-codes/js/index.js' implicitly has an 'any' type.

### ISSUE THREAD

**Issue by SwissMaWi** [pubcore/iso-language-codes#6]
We are getting this error when building code using this package:
[exec] src/library/iso-languages.ts(1,26): error TS7016: Could not find a declaration file for module 'iso-language-codes'. 'D:/BA12/project/src/functions/core/node_modules/iso-language-codes/js/index.js' implicitly has an 'any' type.

I have added a // @ts-ignore to the import as a workaround. However I believe the package should have proper typescript typings.

**Comment by gwmccull** [comment]
I had the same issue so I created an index.d.ts file with the following type:

```
type Code = {
  name: string
  nativeName: string
  iso639_1: string
  iso639_2T: string
  iso639_2B: string
}
declare module 'iso-language-codes' {
  const codes: Code[]
  const by639_1: { [key: string]: Code }
  const by639_2B: { [key: string]: Code }
  const by639_2T: { [key: string]: Code }
  export default codes
  export { codes, by639_1, by639_2B, by639_2T }
}
```

One potential improvement would be to dynamically build enumerated lists for the ISO key values so that they're not just a generic `string`

**Comment by jacklrs** [comment]
Declaration file has been added, thx to @gwmccull ...

**Comment by jacklrs** [comment]
ready for testing ...

**Comment by jacklrs** [comment]
declaration file has been added
